### ISSUE TITLE
[FEATURE] The "intelligent" computer player

### ISSUE THREAD

**Issue by NoNormalCreeper** [kunalshah017/Tic-Tac-Toe#5]
### Description

You said that the feature of this game includes "Intelligent computer player (optional)".

But when I reviewed the source code, I found that the computer player would move completely RANDOMLY.
https://github.com/kunalshah017/Tic-Tac-Toe/blob/fe07a5af0a2783b5fdfab31114a05ebeecaddfd7/main.cpp#L102
```c++
...
void ChooseRandom()
  {
      static std::random_device rd;
      static std::mt19937 gen(rd());
      std::uniform_int_distribution<int> distribution(1, 9);
      comp = distribution(gen);
  }

  void ComputerMove()
  {
      ChooseRandom();
      if (comp >= 1 && comp <= 9)
      {
          if (chars[comp] == '0' + comp)  // int -> char  e.g. '0' + 5 = '5'
          {
              chars[comp] = 'O';
          }
          else
          {
              ComputerMove();
          }
      }
      else
      {
          ComputerMove();
      }
  }
...
``` 

As a result, the computer player wins at a dramaticly low possibility.

So I suggest to give the computer player some intelligence.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to work on this issue

Yes I am willing to submit a PR!

**Comment by NoNormalCreeper** [comment]
Reference: https://www.geeksforgeeks.org/finding-optimal-move-in-tic-tac-toe-using-minimax-algorithm-in-game-theory/

I'll try to implement the algorithm in this repo when I'm free. If you want to write the code yourself you can also assign yourself.

**Comment by kunalshah017** [comment]
Yes this is one good issue you have come up with. this will make the possibilty of wining somewhat better 
As you have choosed to submit a PR I'll assign it to you.
 
Thank You

**Comment by kunalshah017** [comment]
> Reference: https://www.geeksforgeeks.org/finding-optimal-move-in-tic-tac-toe-using-minimax-algorithm-in-game-theory/
> 
> I'll try to implement the algorithm in this repo when I'm free. If you want to write the code yourself you can also assign yourself.

Thanks but you can surely come up with a PR when you are free, I'll also go through the algorithm and try to implement it differently.
